export const timezones = [
  "GMT | Greenwich",
  "GMT+1 | Berlín, Amsterdam, París, Roma, Viena",
  "GMT+2 | Atenas, El Cairo, Estambul, Jerusalén, Kiev",
  "GMT+3 | Estambul, Ankara, Moscú, Nairobi, Riad",
  "GMT+4 | Dubái, Abu Dhabi, Doha, Muscat, Tiflis",
  "GMT+5 | Karachi, Islamabad, Lahore, Nueva Delhi, Tashkent",
  "GMT+6 | Daca, Chittagong, Katmandú, Colombo, Malé",
  "GMT+7 | Bangkok, Hanoi, Ho Chi Minh, Yakarta, Vientiane",
  "GMT+8 | Pekín, Shanghái, Hong Kong, Kuala Lumpur, Singapur",
  "GMT+9 | Tokio, Osaka, Seúl, Taipei, Ulaanbaatar",
  "GMT+10 | Sídney, Melbourne, Brisbane, Port Moresby, Numea",
  "GMT+11 | Suva, Apia, Nuku'alofa, Port Vila, Honiara",
  "GMT+12 | Auckland, Wellington, Christchurch, Suva, Pago Pago",
  "GMT-1 | Azores, Islas Canarias, Cabo Verde",
  "GMT-2 | Mid-Atlantic, Fernando de Noronha, São Paulo",
  "GMT-3 | Buenos Aires, Brasilia, Montevideo, Santiago, Georgetown",
  "GMT-4 | Santiago, Valparaíso, La Paz, Caracas, Santo Domingo",
  "GMT-5 | Ciudad de México, Chicago, Bogotá, Lima, Quito",
  "GMT-6 | Chicago, Denver, Dallas, Ciudad de Guatemala, San José",
  "GMT-7 | Denver, Phoenix, Los Ángeles, Calgary, Edmonton",
  "GMT-8 | Los Ángeles",
  "GMT-9 | Anchorage, Honolulu",
  "GMT-10 | Honolulu, Pago Pago",
  "GMT-11 | Pago Pago",
  "GMT-12 | Baker Island"
];
