export const timezones = [
  "GMT | Greenwich, Reino Unido",
  "GMT+1 | Berlín, Alemania (Amsterdam, París, Roma, Viena)",
  "GMT+2 | Atenas, Grecia (El Cairo, Estambul, Jerusalén, Kiev)",
  "GMT+3 | Estambul, Turquía (Ankara, Moscú, Nairobi, Riad)",
  "GMT+4 | Dubái, Emiratos Árabes Unidos (Abu Dhabi, Doha, Muscat, Tiflis)",
  "GMT+5 | Karachi, Pakistán (Islamabad, Lahore, Nueva Delhi, Tashkent)",
  "GMT+6 | Daca, Bangladesh (Chittagong, Katmandú, Colombo, Malé)",
  "GMT+7 | Bangkok, Tailandia (Hanoi, Ho Chi Minh, Yakarta, Vientiane)",
  "GMT+8 | Pekín, China (Shanghái, Hong Kong, Kuala Lumpur, Singapur)",
  "GMT+9 | Tokio, Japón (Osaka, Seúl, Taipei, Ulaanbaatar)",
  "GMT+10 | Sídney, Australia (Melbourne, Brisbane, Port Moresby, Numea)",
  "GMT+11 | Suva, Fiyi (Apia, Nuku'alofa, Port Vila, Honiara)",
  "GMT+12 | Auckland, Nueva Zelanda (Wellington, Christchurch, Suva, Pago Pago)",
  "GMT-1 | Azores, Portugal (Islas Canarias, Cabo Verde)",
  "GMT-2 | Mid-Atlantic, Brasil (Fernando de Noronha, São Paulo)",
  "GMT-3 | Buenos Aires, Argentina (Brasilia, Montevideo, Santiago, Georgetown)",
  "GMT-4 | Santiago, Chile (Valparaíso, La Paz, Caracas, Santo Domingo)",
  "GMT-5 | Ciudad de México, México (Chicago, Bogotá, Lima, Quito)",
  "GMT-6 | Chicago, Estados Unidos (Denver, Dallas, Ciudad de Guatemala, San José)",
  "GMT-7 | Denver, Estados Unidos (Phoenix, Los Ángeles, Calgary, Edmonton)",
  "GMT-8 | Los Ángeles, Estados Unidos (San Francisco, Vancouver, Anchorage, Tijuana)",
  "GMT-9 | Anchorage, Estados Unidos (Honolulu)",
  "GMT-10 | Honolulu, Estados Unidos (Pago Pago)",
  "GMT-11 | Pago Pago, Samoa",
  "GMT-12 | Baker Island, Estados Unidos"
];

