export const usersData = [
  {
    userId: 1,
    firstName: "Roberto",
    lastName: "Gómez",
    email: "user1@example.com",
    password: "1234",
    photo: "/images/user1img.jpeg",
  },
  {
    userId: 2,
    firstName: "Laura",
    lastName: "Rodríguez",
    email: "user2@example.com",
    password: "1234",
    photo: "/images/user2img.jpg",
  },
  {
    userId: 3,
    firstName: "Samuel",
    lastName: "Pérez",
    email: "user3@example.com",
    password: "1234",
    photo: "/images/user3img.jpg",
  },
  {
    userId: 4,
    firstName: "Juan",
    lastName: "Almeida",
    email: "user4@example.com",
    password: "1234",
    photo: "/images/user4img.jpg",
  },
  {
    userId: 5,
    firstName: "Luciana",
    lastName: "Acosta",
    email: "user5@example.com",
    password: "1234",
    photo: "/images/user5img.jpg",
  },
];
