export const usersData = [
  {
    userId: "1",
    firstName: "user1",
    lastName: "test",
    email: "user1@example.com",
    password: "1234",
    photo: "/images/user1img.jpeg",
  },
  {
    userId: "2",
    firstName: "user2",
    lastName: "test",
    email: "user2@example.com",
    password: "1234",
    photo: "/images/user2img.jpg",
  },
  {
    userId: "3",
    firstName: "user3",
    lastName: "test",
    email: "user3@example.com",
    password: "1234",
    photo: "/images/user3img.jpg",
  },
  {
    userId: "4",
    firstName: "user4",
    lastName: "test",
    email: "user4@example.com",
    password: "1234",
    photo: "/images/user4img.jpg",
  },
  {
    userId: "5",
    firstName: "user5",
    lastName: "test",
    email: "user5@example.com",
    password: "1234",
    photo: "/images/user5img.jpg",
  },
];
